### PR TITLE
Added missing requirements

### LINKED ISSUE #27: Missing packages in requirements.in
I think there are 2 packages missing in the requirements.in: bcrypt and pyjwt.

Without adding them to the file, the project installed with a virtualenv doesn't seem to work. At first it was suggested that it might be a Windows only thing, but after Alejandro with MAC needed to also add them in order for the project to work I'm quite confident they are indeed needed.

### PR DESCRIPTION
**Pull request by andreu-vall**
Same as before branching from the correct site.

'''
I added 2 requirements in the file requirements.in that were needed for me, Alejandro and Ivan.

Before merging can you check that it still works in your computer @BlessedLongsword or @xvxnoah
'''

### CODE REVIEW

**Review by BlessedLongsword — COMMENTED** [review]
I am not completely convinced by this. The way linux (or python 3.11) compiles the requirements is different from windows (or python 3.10). I executed the pip-compile and the requirements changed.

image

**Comment by BlessedLongsword** [comment]
I suggest that we put the requirements in the git ignore for development, and ultimately change it for when we dockerize it so that it has the indispensable. We won't need requirements.txt in the docker since we can generate it from there in the dockerfile.

**Comment by andreu-vall** [comment]
Putting the requirements.txt as private looks good to me

**Review by BlessedLongsword — APPROVED** [review]
Okay, seems fine, remember to test for minimal requirements when dockerizing.

**Pull request merged**
