### PR TITLE
[Enhancement]: Send welcome email

### LINKED ISSUE #64: US1-BE#100 - Send welcome email

### PR DESCRIPTION
**Pull request by xvxnoah**
Now after successful register, user will get a welcome email:
welcome_email

### CODE REVIEW

**Review by BlessedLongsword — DISMISSED** [review]
Good job, now you only need to fix the tests.

**Review by BlessedLongsword — DISMISSED** [review]

**Comment by andreu-vall** [comment]
I've just tried it, uncommenting the "send_welcome_email" and adding the environment variables for the email it is indeed working 👍 . I'll add the environment variables to make the tests also work and accept the PR soon

**Comment by andreu-vall** [comment]
For me the attributes for the email are not being put in the email correctly:
image
Everything appears to be in the "from" field

**Comment by andreu-vall** [comment]
Ups I think I ran the tests with the kasuladb Database. I'll change it manually from the run_tests.py script because it deletes everything in the database 😢

**Comment by andreu-vall** [comment]
> For me the attributes for the email are not being put in the email correctly: image Everything appears to be in the "from" field

Looks like it was done this way, which is a bit weird, I'll check if I can put it in the fields

**Review by andreu-vall — APPROVED** [review]
Now all the tests are passing and the email is sent correctly. Everything looks good!

**Pull request merged**
