### PR TITLE
[Testing]: Recipe Endpoints

### LINKED ISSUE #48: [Testing]: Recipe Endpoints
Implementation of unit tests for the recipe endpoints in the backend to ensure the stability and reliability of our backend services.

### PR DESCRIPTION
**Pull request by xvxnoah**
To test these endpoints, we will focus on the following testing parameters:

1. Happy Path: Testing when everything goes as expected.

2. Boundary/Edge Cases: Testing with the extremes.

3. Error Cases: Testing where we expect errors or failures.

### CODE REVIEW

**Review by BlessedLongsword — DISMISSED** [review]
Okay, as it is now it is acceptable, however we need to consider this for the future

- We should reset the database on test start to avoid errors in case there are residual entries.
- Create more unit tests, especially ones asserting failures. This, however, is not a priority, as the frontend should be integrated to avoid fail cases. It is more focused on requests through postman (for security purposes).

**Comment by andreu-vall** [comment]
Yeah indeed we should reset the database. It has happened to me a few times that the tests crashed for some reason, and then there is unexpected users in the database and then all the tests fail

**Comment by xvxnoah** [comment]
> Yeah indeed we should reset the database. It has happened to me a few times that the tests crashed for some reason, and then there is unexpected users in the database and then all the tests fail

With the last commit that gets solved.

**Review by BlessedLongsword — DISMISSED** [review]
Everything seems fine now, good job!

**Review by BlessedLongsword — DISMISSED** [review]

**Review by BlessedLongsword — APPROVED** [review]

**Pull request merged**
