### PR TITLE
[Enhancement]: Add timestamp to models

### LINKED ISSUE #66: US5-BE#100 Add timestamps to models
We might need this in the future so, given that there are going to be a lot of backend changes this is actually a very important thing to work on. Create a timestamp model including two timestamps:

- Creation date
- Las modification date
- (any other thing you find appropriate)

This are very important data that can be used in the future for things like filtering.

### PR DESCRIPTION
**Pull request by xvxnoah**
We might need this in the future so, given that there are going to be a lot of backend changes this is actually a very important thing to work on. Create a timestamp model including two timestamps:

- Creation date
- Las modification date

This are very important data that can be used in the future for things like filtering.

### CODE REVIEW

**Review by BlessedLongsword — CHANGES_REQUESTED** [review]
I would also add an edition date for put methods, especially for things like recipe, if we want to filter by last modified. This field can be None by default.

**Comment by andreu-vall** [comment]
So far looks good to me 👍

**Comment by andreu-vall** [comment]
As Antonio commented, will you also add the last modification date field?

**Comment by xvxnoah** [comment]
> As Antonio commented, will you also add the last modification date field?

Working on it.

**Comment by andreu-vall** [comment]
Ok now last modification field has been added. But I think the code to update this field when the document is updated through 'PUT' is still missing

**Comment by andreu-vall** [comment]
> Ok now last modification field has been added. But I think the code to update this field when the document is updated through 'PUT' is still missing

Ups I somehow misread the code, it is indeed updated. Tomorrow I will manually execute the code to check that it is indeed working, but everything looks correct

**Review by BlessedLongsword — APPROVED** [review]

**Pull request merged**
